spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistemainterno?useSSL=false
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false  
